### ISSUE TITLE
unbound variable error thrown when running on AWS linux

### ISSUE THREAD

**Issue by sutaakar** [container-tools/kind-action#9]
I tried to run the action on my AWS runner based on Amazon Linux.
When I run action:
```
    - name: Set up KinD
      uses: container-tools/kind-action@v2
      with:
        config: .github/kind-config.yaml
        registry: true
        node_image: kindest/node:v1.22.2
```
I get an error:
```
/actions-runner/_work/_actions/container-tools/kind-action/v2/main.sh: line 66: args[@]: unbound variable
```

Can you please check what is the issue?
